name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches:
      - trunk
      - releases/*
    types:
      - completed

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish-to-gpr:
    name: Publish to GitHub Packages

    if: contains(github.ref, 'trunk')

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download packages artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: continuous-integration.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: packages

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/asiffermann/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages to GPR
        run: dotnet nuget push *.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}

  publish-to-nuget:
    name: Publish to NuGet.org

    if: contains(github.ref, 'releases')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download packages artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: continuous-integration.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: packages

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGETAPIKEY }}

      - name: Publish packages to NuGet.org
        run: dotnet nuget push *.nupkg --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}