name: Releases

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Continuous Integration']
    branches:
      - releases/*
    types:
      - completed

jobs:
  gitversion:
    name: Calculate SemVer

    runs-on: ubuntu-latest

    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: 5.x

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

  create-release:
    name: Create GitHub release

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    needs: gitversion
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download packages artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: continuous-integration.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: packages
          branch: ${{ github.ref }}

      - name: Get commit message
        run: |
          echo "commitMessage=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.gitversion.outputs.fullSemVer }}
          commit: ${{ github.sha }}
          draft: true
          body: ${{ env.commitMessage }}
          artifacts: '*.nupkg'
          discussionCategory: Releases
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}