name: Unit tests results (external PRs)

on:
   workflow_run:
      workflows: ["Continuous Integration"]
      types:
         - completed

jobs:
   unit-tests-results:
      name: Publish unit tests results
      runs-on: ubuntu-latest
      if: >
         github.event.workflow_run.conclusion != 'skipped' && (
            github.event.sender.login == 'dependabot[bot]' ||
            github.event.workflow_run.head_repository.full_name != github.repository
         )

      steps:
         - name: Download artifacts
           uses: actions/github-script@v3
           with:
              script: |
                 var fs = require('fs');
                 var path = require('path');
                 var artifacts_path = path.join('${{github.workspace}}', 'artifacts');
                 fs.mkdirSync(artifacts_path, { recursive: true });

                 var artifacts = await github.actions.listWorkflowRunArtifacts({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: ${{ github.event.workflow_run.id }},
                 });

                 for (const artifact of artifacts.data.artifacts) {
                    if (artifact.name === 'tests-results') {
                      var download = await github.actions.downloadArtifact({
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                         artifact_id: artifact.id,
                         archive_format: 'zip',
                      });
                      var artifact_path = path.join(artifacts_path, `${artifact.name}.zip`)
                      fs.writeFileSync(artifact_path, Buffer.from(download.data));
                      console.log(`Downloaded ${artifact_path}`);
                    }
                 }

         - name: Extract artifacts
           run: |
              for file in artifacts/*.zip
              do
                if [ -f "$file" ]
                then
                  dir="${file/%.zip/}"
                  mkdir -p "$dir"
                  unzip -d "$dir" "$file"
                fi
              done

         - name: Publish unit tests results
           uses: EnricoMi/publish-unit-test-result-action@v1.15
           with:
              commit: ${{ github.event.workflow_run.head_sha }}
              files: "artifacts/tests-results/*.junit.xml"
              check_name: "Unit tests results"
              comment_on_pr: false